services:
  bot-rental:
    build: 
      context: ..
      dockerfile: backend/Dockerfile
    container_name: bot-rental
    ports: 
      - "${FASTAPI_PORT}:8000"
    command: "uvicorn --factory src.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    volumes:
      - ../backend:/app 
    networks:
      - backend

networks:
  backend:
    driver: bridge