services:
  bot:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: bot
    volumes:
      - ../backend:/app
    command: python -m bot.run
    env_file:
      - ../.env
    networks:
      - backend